version: '3'
services:
  flask:
    build:
      context: .
      dockerfile: docker/Dockerfile
    volumes:
      - ./app:/var/app/
    ports:
      - 5000:5000
    working_dir: /var/app
    environment:
      FLASK_APP: app.py
      FLASK_ENV: development
    command: flask run --host=0.0.0.0
