FROM python:3-alpine

LABEL maintainer="João Pedro Pinheiro <joaopedro.pinheiro88@gmail.com>"

RUN pip3 install --no-cache-dir --upgrade pip \
 && pip3 install Flask==1.1.1                 \
                 peewee==3.9.6
